### ISSUE TITLE
Create csv with all the ICANN mailinglist data

### ISSUE THREAD

**Issue by nllz** [nllz/bigbang#10]

**Comment by sbenthall** [comment]
See #12 and #13 for solved issues with ICANN import

**Comment by nllz** [comment]
Probably easier if we create a csv (and add it to /examples) with all the data instead of letting everyone import everything?

**Comment by nllz** [comment]
It fails at the metric.sc list:
'retrieving http://mm.icann.org/pipermail/metrics.sc/2015-February.txt.gz'
200 - writing file to archives/http://mm.icann.org/pipermail/metrics.sc/2015-February.txt.gz
'retrieving http://mm.icann.org/pipermail/metrics.sc/2015-January.txt.gz'
200 - writing file to archives/http://mm.icann.org/pipermail/metrics.sc/2015-January.txt.gz
'retrieving http://mm.icann.org/pipermail/metrics.sc/2014-December.txt.gz'
200 - writing file to archives/http://mm.icann.org/pipermail/metrics.sc/2014-December.txt.gz
'retrieving http://mm.icann.org/pipermail/metrics.sc/2014-November.txt.gz'
200 - writing file to archives/http://mm.icann.org/pipermail/metrics.sc/2014-November.txt.gz
'retrieving http://mm.icann.org/pipermail/metrics.sc/2014-October.txt.gz'
200 - writing file to archives/http://mm.icann.org/pipermail/metrics.sc/2014-October.txt.gz
'retrieving http://mm.icann.org/pipermail/metrics.sc/2014-September.txt.gz'
200 - writing file to archives/http://mm.icann.org/pipermail/metrics.sc/2014-September.txt.gz
'retrieving http://mm.icann.org/pipermail/metrics.sc/2014-March.txt.gz'
200 - writing file to archives/http://mm.icann.org/pipermail/metrics.sc/2014-March.txt.gz
'retrieving http://mm.icann.org/pipermail/metrics.sc/2014-February.txt.gz'
200 - writing file to archives/http://mm.icann.org/pipermail/metrics.sc/2014-February.txt.gz
'retrieving http://mm.icann.org/pipermail/metrics.sc/2014-January.txt.gz'
200 - writing file to archives/http://mm.icann.org/pipermail/metrics.sc/2014-January.txt.gz
'retrieving http://mm.icann.org/pipermail/metrics.sc/2013-December.txt.gz'
200 - writing file to archives/http://mm.icann.org/pipermail/metrics.sc/2013-December.txt.gz
'retrieving http://mm.icann.org/pipermail/metrics.sc/2013-November.txt.gz'
200 - writing file to archives/http://mm.icann.org/pipermail/metrics.sc/2013-November.txt.gz
'retrieving http://mm.icann.org/pipermail/metrics.sc/2013-October.txt.gz'
200 - writing file to archives/http://mm.icann.org/pipermail/metrics.sc/2013-October.txt.gz
'retrieving http://mm.icann.org/pipermail/metrics.sc/2013-September.txt.gz'
200 - writing file to archives/http://mm.icann.org/pipermail/metrics.sc/2013-September.txt.gz
'retrieving http://mm.icann.org/pipermail/metrics.sc/2013-August.txt.gz'
200 - writing file to archives/http://mm.icann.org/pipermail/metrics.sc/2013-August.txt.gz
'retrieving http://mm.icann.org/pipermail/metrics.sc/2012-December.txt.gz'
200 - writing file to archives/http://mm.icann.org/pipermail/metrics.sc/2012-December.txt.gz
'retrieving http://mm.icann.org/pipermail/metrics.sc/2012-September.txt.gz'
200 - writing file to archives/http://mm.icann.org/pipermail/metrics.sc/2012-September.txt.gz
'retrieving http://mm.icann.org/pipermail/metrics.sc/2012-August.txt.gz'
200 - writing file to archives/http://mm.icann.org/pipermail/metrics.sc/2012-August.txt.gz
'retrieving http://mm.icann.org/pipermail/metrics.sc/2012-July.txt.gz'
200 - writing file to archives/http://mm.icann.org/pipermail/metrics.sc/2012-July.txt.gz
'retrieving http://mm.icann.org/pipermail/metrics.sc/2012-June.txt.gz'
200 - writing file to archives/http://mm.icann.org/pipermail/metrics.sc/2012-June.txt.gz
'retrieving http://mm.icann.org/pipermail/metrics.sc/2012-May.txt.gz'
200 - writing file to archives/http://mm.icann.org/pipermail/metrics.sc/2012-May.txt.gz
'retrieving http://mm.icann.org/pipermail/metrics.sc/2012-April.txt.gz'
200 - writing file to archives/http://mm.icann.org/pipermail/metrics.sc/2012-April.txt.gz
unzipping 21 archive files
Opening 21 archive files
/home/gogol/Data/bigbang/bigbang/mailman.py:109: UserWarning: No mailing list name found at http://mm.icann.org/pipermail/mm.icann.org.txt
  warnings.warn("No mailing list name found at %s" % url)
'Getting archive page for http://mm.icann.org/pipermail/mm.icann.org.txt'
Traceback (most recent call last):
  File "bin/collect_mail.py", line 41, in <module>
    main(sys.argv[1:])
  File "bin/collect_mail.py", line 38, in main
    mailman.collect_from_file(arg)
  File "/home/gogol/Data/bigbang/bigbang/mailman.py", line 98, in collect_from_file
    collect_from_url(url)
  File "/home/gogol/Data/bigbang/bigbang/mailman.py", line 80, in collect_from_url
    has_archives = collect_archive_from_url(url)
  File "/home/gogol/Data/bigbang/bigbang/mailman.py", line 134, in collect_archive_from_url
    response = urllib2.urlopen(url)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

**Comment by sbenthall** [comment]
This appears to be because there's no mailing list archive page at this address:

http://mm.icann.org/pipermail/mm.icann.org.txt

I think this address is on the list in error. It's the name of a filename, and it's not included on this list here:

https://mm.icann.org/mailman/listinfo

I'm going to remove this from the list of ICANN mailman urls

**Comment by nllz** [comment]
You'e right. Removed now. Will restart import.

**Comment by nllz** [comment]
Do you think we should let the students import the lists or we create a csv from which the notebook pull their data?

**Comment by nllz** [comment]
Hmmmm. It fails at the public-comment list. Is this because it links to mailman folder instead of pipermail? And might this be the case because the mailinglist is closed?

/home/gogol/Data/bigbang/bigbang/mailman.py:109: UserWarning: No mailing list name found at http://mm.icann.org/pipermail/public-comment
  warnings.warn("No mailing list name found at %s" % url)
'Getting archive page for http://mm.icann.org/pipermail/public-comment'
Traceback (most recent call last):
  File "bin/collect_mail.py", line 41, in <module>
    main(sys.argv[1:])
  File "bin/collect_mail.py", line 38, in main
    mailman.collect_from_file(arg)
  File "/home/gogol/Data/bigbang/bigbang/mailman.py", line 98, in collect_from_file
    collect_from_url(url)
  File "/home/gogol/Data/bigbang/bigbang/mailman.py", line 80, in collect_from_url
    has_archives = collect_archive_from_url(url)
  File "/home/gogol/Data/bigbang/bigbang/mailman.py", line 134, in collect_archive_from_url
    response = urllib2.urlopen(url)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

**Comment by sbenthall** [comment]
I think we should give students the data because if 20 people all try to collect the data from the ICANN mailman servers at the same time, that could cause problems.

**Comment by sbenthall** [comment]
Re: http://mm.icann.org/pipermail/public-comment

_Public-comment_ is listed in the mailman list index:
https://mm.icann.org/mailman/listinfo

But the archive page itself has an unexpected URL because the archive is private:
https://mm.icann.org/mailman/listinfo/public-comment link to archives says _(currently available only to list members)_
https://mm.icann.org/mailman/private/public-comment/

Interesting that the public comments are private...

**Comment by sbenthall** [comment]
Seems like it should just skip the list in this case.

**Comment by nllz** [comment]
It's interesting because this seems to work:

$ python bin/collect_mail.py -u https://mm.icann.org/mailman/listinfo/public-comment
/home/gogol/Data/bigbang/bigbang/mailman.py:109: UserWarning: No mailing list name found at https://mm.icann.org/mailman/listinfo/public-comment
  warnings.warn("No mailing list name found at %s" % url)
'Getting archive page for https://mm.icann.org/mailman/listinfo/public-comment'
[]

but with the mass import script I keep on getting:

  warnings.warn("No mailing list name found at %s" % url)
'Getting archive page for http://mm.icann.org/pipermail/psc-liaison'
[]
/home/gogol/Data/bigbang/bigbang/mailman.py:109: UserWarning: No mailing list name found at http://mm.icann.org/pipermail/public-comment
  warnings.warn("No mailing list name found at %s" % url)
'Getting archive page for http://mm.icann.org/pipermail/public-comment'
Traceback (most recent call last):
  File "bin/collect_mail.py", line 41, in <module>
    main(sys.argv[1:])
  File "bin/collect_mail.py", line 38, in main
    mailman.collect_from_file(arg)
  File "/home/gogol/Data/bigbang/bigbang/mailman.py", line 98, in collect_from_file
    collect_from_url(url)
  File "/home/gogol/Data/bigbang/bigbang/mailman.py", line 80, in collect_from_url
    has_archives = collect_archive_from_url(url)
  File "/home/gogol/Data/bigbang/bigbang/mailman.py", line 134, in collect_archive_from_url
    response = urllib2.urlopen(url)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

**Comment by sbenthall** [comment]
This commit causes a graceful failure when for whatever reason there isn't an archive page at the specified URL.

You may want to consider removing the faulty URL from the mm.icann.org.txt file entirely.

https://github.com/nllz/bigbang/commit/ba2ed91b622c542384e178fc16912a882f4acb6a

**Comment by nllz** [comment]
weird, am now getting (but will pull and try again): 

'Getting archive page for http://mm.icann.org/pipermail/gnso-rds-pdp-wg'
Traceback (most recent call last):
  File "bin/collect_mail.py", line 41, in <module>
    main(sys.argv[1:])
  File "bin/collect_mail.py", line 38, in main
    mailman.collect_from_file(arg)
  File "/home/gogol/Data/bigbang/bigbang/mailman.py", line 98, in collect_from_file
    collect_from_url(url)
  File "/home/gogol/Data/bigbang/bigbang/mailman.py", line 80, in collect_from_url
    has_archives = collect_archive_from_url(url)
  File "/home/gogol/Data/bigbang/bigbang/mailman.py", line 134, in collect_archive_from_url
    response = urllib2.urlopen(url)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 101] Network is unreachable>

**Comment by sbenthall** [comment]
I'm not getting this error locally.
It may be due to a temporary network glitch on your end.
Can you reproduce the problem?

**Comment by nllz** [comment]
pulled and now that seems to go OK, but we seem to be back in unicode hell:

200 - writing file to archives/http://mm.icann.org/pipermail/tz/1986-November.txt.gz
unzipping 312 archive files
Opening 312 archive files
Date parsing error on: 
Sun, 1 Feb 87 17:17:55 est
Date parsing error on: 
Thu, 5 Feb 87 16:36:28 pst
Date parsing error on: 
Fri, 6 Feb 87 19:08:02 est
Date parsing error on: 
Sun, 8 Feb 87 21:35:31 est
Date parsing error on: 
Wed, 11 Feb 87 11:18:30 est
Date parsing error on: 
Wed, 11 Feb 87 11:45:36 est
Date parsing error on: 
Wed, 18 Feb 87 08:55:26 pst
Date parsing error on: 
Sun, 1 Feb 87 17:17:55 est
Date parsing error on: 
Thu, 5 Feb 87 16:36:28 pst
Date parsing error on: 
Fri, 6 Feb 87 19:08:02 est
Date parsing error on: 
Sun, 8 Feb 87 21:35:31 est
Date parsing error on: 
Wed, 11 Feb 87 11:18:30 est
Date parsing error on: 
Wed, 11 Feb 87 11:45:36 est
Date parsing error on: 
Wed, 18 Feb 87 08:55:26 pst
Date parsing error on: 
Wed, 03 Sep 97 10:34:06 Pacific Daylight Time
Date parsing error on: 
Wed, 03 Sep 97 10:34:06 Pacific Daylight Time
Date parsing error on: 
Wed, 30 Jul 1997 23:59:60 -0700
Date parsing error on: 
Mon, 30 Jun 1997 16:59:60 -0700 
Date parsing error on: 
Wed, 30 Jul 1997 23:59:60 -0700
Date parsing error on: 
Mon, 30 Jun 1997 16:59:60 -0700 
Date parsing error on: 
Thu, 5 Mar 87 03:37:17 est
Date parsing error on: 
Tue, 10 Mar 87 10:00:19 cst
Date parsing error on: 
Sat, 14 Mar 87 16:32:43 est
Date parsing error on: 
Mon, 16 Mar 87 14:54:46 cst
Date parsing error on: 
Mon, 30 Mar 87 12:07:02 pst
Date parsing error on: 
Thu, 5 Mar 87 03:37:17 est
Date parsing error on: 
Tue, 10 Mar 87 10:00:19 cst
Date parsing error on: 
Sat, 14 Mar 87 16:32:43 est
Date parsing error on: 
Mon, 16 Mar 87 14:54:46 cst
Date parsing error on: 
Mon, 30 Mar 87 12:07:02 pst
Date parsing error on: 
Thu, 23 Jul 87 11:12:18 pdt
Date parsing error on: 
Thu, 23 Jul 87 11:12:18 pdt
Date parsing error on: 
Sun, 7 Dec 86 14:52:04 est
Date parsing error on: 
Mon, 8 Dec 86 13:27:34 est
Date parsing error on: 
Tue, 9 Dec 86 11:33:44 cst
Date parsing error on: 
Thu, 11 Dec 86 16:12:28 cst
Date parsing error on: 
Mon, 15 Dec 86 09:56:21 cst
Date parsing error on: 
Wed, 17 Dec 86 11:09:09 cst
Date parsing error on: 
Thu, 18 Dec 86 06:57:09 cst
Date parsing error on: 
Fri, 19 Dec 86 14:26:27 est
Date parsing error on: 
Wed, 17 Dec 86 16:20:16 mst
Date parsing error on: 
Sun, 7 Dec 86 14:52:04 est
Date parsing error on: 
Mon, 8 Dec 86 13:27:34 est
Date parsing error on: 
Tue, 9 Dec 86 11:33:44 cst
Date parsing error on: 
Thu, 11 Dec 86 16:12:28 cst
Date parsing error on: 
Mon, 15 Dec 86 09:56:21 cst
Date parsing error on: 
Wed, 17 Dec 86 11:09:09 cst
Date parsing error on: 
Thu, 18 Dec 86 06:57:09 cst
Date parsing error on: 
Fri, 19 Dec 86 14:26:27 est
Date parsing error on: 
Wed, 17 Dec 86 16:20:16 mst
Date parsing error on: 
Thu, 2 Apr 87 15:12:35 mst
Date parsing error on: 
Mon, 6 Apr 87 00:11:07 pst
Date parsing error on: 
Wed, 8 Apr 87 10:17:34 est
Date parsing error on: 
Sun, 12 Apr 87 11:56:11 est
Date parsing error on: 
Sun, 12 Apr 87 13:16:43 est
Date parsing error on: 
Mon, 13 Apr 87 14:31:20 est
Date parsing error on: 
Wed, 22 Apr 87 11:59:47 est
Date parsing error on: 
Thu, 2 Apr 87 15:12:35 mst
Date parsing error on: 
Mon, 6 Apr 87 00:11:07 pst
Date parsing error on: 
Wed, 8 Apr 87 10:17:34 est
Date parsing error on: 
Sun, 12 Apr 87 11:56:11 est
Date parsing error on: 
Sun, 12 Apr 87 13:16:43 est
Date parsing error on: 
Mon, 13 Apr 87 14:31:20 est
Date parsing error on: 
Wed, 22 Apr 87 11:59:47 est
Date parsing error on: 
Mon, 12 Jul 99 11:58:23 WETDST
Date parsing error on: 
Mon, 12 Jul 99 11:58:23 WETDST
Date parsing error on: 
Fri, 1 May 87 09:34:08 cdt
Date parsing error on: 
Sun, 3 May 87 14:20:23 est
Date parsing error on: 
Sun, 3 May 87 14:26:31 est
Date parsing error on: 
Sun, 3 May 87 15:06:58 est
Date parsing error on: 
Fri, 1 May 87 09:34:08 cdt
Date parsing error on: 
Sun, 3 May 87 14:20:23 est
Date parsing error on: 
Sun, 3 May 87 14:26:31 est
Date parsing error on: 
Sun, 3 May 87 15:06:58 est
Date parsing error on: 
Mon, 6 Jun 88 13:59:13 mdt
Date parsing error on: 
Mon, 6 Jun 88 13:59:13 mdt
Traceback (most recent call last):
  File "bin/collect_mail.py", line 41, in <module>
    main(sys.argv[1:])
  File "bin/collect_mail.py", line 38, in main
    mailman.collect_from_file(arg)
  File "/home/gogol/Data/bigbang/bigbang/mailman.py", line 102, in collect_from_file
    collect_from_url(url)
  File "/home/gogol/Data/bigbang/bigbang/mailman.py", line 93, in collect_from_url
    data.to_csv(path, ",", encoding="utf-8")
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/site-packages/pandas/core/frame.py", line 1344, in to_csv
    formatter.save()
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/site-packages/pandas/formats/format.py", line 1551, in save
    self._save()
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/site-packages/pandas/formats/format.py", line 1652, in _save
    self._save_chunk(start_i, end_i)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/site-packages/pandas/formats/format.py", line 1678, in _save_chunk
    lib.write_csv_rows(self.data, ix, self.nlevels, self.cols, self.writer)
  File "pandas/lib.pyx", line 1058, in pandas.lib.write_csv_rows (pandas/lib.c:19481)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/site-packages/pandas/io/common.py", line 522, in writerows
    data = data.decode("utf-8")
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xef in position 265029: invalid continuation byte

**Comment by sbenthall** [comment]
Yes, I see it.

For these very long stack traces, please consider pasting them into a gist like this:
https://gist.github.com/anonymous/b49e5daa5dd73b248694aa4c60633d93

**Comment by nllz** [comment]
oks - sry :)

**Comment by sbenthall** [comment]
No problem :)

Hmmm. All those date parsing errors are also a little worrisome :/

**Comment by sbenthall** [comment]
Ironically, the date parsing errors are coming from the mailing list devoted to discussion of timezones (tz) ?

**Comment by nllz** [comment]
The irony did not escape me :)

**Comment by sbenthall** [comment]
This is a workaround for the latest problem, which is with the CSV encoding of data from the `tz` mailing list.

https://github.com/nllz/bigbang/commit/20b2b5c169619f016f659d6cea3f82265a379ea3

**Comment by sbenthall** [comment]
The last remaining problem has to do with these irregular archive URLS in `mm.icann.org.txt` :

```
http://lists.ncuc.org/cgi-bin/mailman/listinfo/bylaws
http://lists.ncuc.org/cgi-bin/mailman/listinfo/e-team
http://lists.ncuc.org/cgi-bin/mailman/listinfo/membership-affairs
http://lists.ncuc.org/cgi-bin/mailman/listinfo/ncuc-af
http://lists.ncuc.org/cgi-bin/mailman/listinfo/ncuc-ap
http://lists.ncuc.org/cgi-bin/mailman/listinfo/ncuc-discuss
http://lists.ncuc.org/cgi-bin/mailman/listinfo/ncuc-ec
http://lists.ncuc.org/cgi-bin/mailman/listinfo/ncuc-eur
http://lists.ncuc.org/cgi-bin/mailman/listinfo/ncuc-lac
http://lists.ncuc.org/cgi-bin/mailman/listinfo/ncuc-na
http://lists.ncuc.org/cgi-bin/mailman/listinfo/pt53
https://listserv.syr.edu/scripts/wa.exe?A0=NCSG-DISCUSS
```

BigBang isn't finding the archives fro the lists.ncuc.org lists. I think it might have better luck you the mm.icann.org.txt file pointed to the pipermail archive pages like so:

http://lists.ncuc.org/pipermail/bylaws/

As for NCSG-DISCUSS...that looks like a very irregular web archive. I'm not sure what can be done to get that data without writing a custom script for it.

**Comment by sbenthall** [comment]
Ah, the NCSG mailing list is not hosted  using [Mailman](https://www.gnu.org/software/mailman/), but rather using [LISTSERV](http://www.lsoft.com/products/listserv.asp), a different piece of software.

If that data is important...is there a way you can contact the administrator of that mailing list and ask them for the archive as an .mbox file?

**Comment by nllz** [comment]
Already pinged the admin for NCSG with exactly that question. 

Are you suggesting I add the ncuc archive pages manually to mm.icann.org.txt? If so, that's not a problem.

**Comment by nllz** [comment]
That would be this:
http://lists.ncuc.org/pipermail/bylaws/
http://lists.ncuc.org/pipermail/e-team
http://lists.ncuc.org/pipermail/membership-affairs
http://lists.ncuc.org/pipermail/ncuc-af
http://lists.ncuc.org/pipermail/ncuc-ap
http://lists.ncuc.org/pipermail/ncuc-discuss
http://lists.ncuc.org/pipermail/ncuc-ec
http://lists.ncuc.org/pipermail/ncuc-eur
http://lists.ncuc.org/pipermail/ncuc-lac
http://lists.ncuc.org/pipermail/ncuc-na
http://lists.ncuc.org/pipermail/pt53

**Comment by nllz** [comment]
updated mm.icann.org.txt and importing now

**Comment by sbenthall** [comment]
Downloading all the mailing list data and turning each individual list into .csv is working for me locally.
I think all that's left is bundling the .csv files into a single compressed file.
It may also be good to test loading the data as bigbang.Archive objects.

**Comment by nllz** [comment]
I might be getting ahead of myself, but how do I put the archives in a csv file that is readable by the notebooks?

**Comment by nllz** [comment]
Comment crossfire

**Comment by sbenthall** [comment]
See https://github.com/nllz/bigbang/issues/14

Something is working unexpectedly in the way BigBang is setting file system paths for each archive, so it's a little harder to get at than it should be.

But you should be able to navigate to the .csv files as a subdirectory of the bigbang directory you cloned from GitHub.

For example I can see many .csv files here:

ls archives/http\:/mm.icann.org/pipermail/*.csv

There's another bunch at:

ls archives/http\:/mm.icann.org/pipermail/*.csv
ls archives/http\:/lists.ncuc.org/pipermail/*.csv

**Comment by sbenthall** [comment]
oh, sorry, those should be asterisks
ls archives/http:/mm.icann.org/pipermail/*.csv

**Comment by sbenthall** [comment]
So, in a Jupyter notebook you can try for any individual list:

```
from bigbang.archive import Archive
arx = Archive("http://mm.icann.org/pipermail/vip",archive_dir="../archives")
arx.data
```

And start to play around.

I'm going to try to get the full ICANN .csv dump in a tar.gz and hosted somewhere you can point to.

**Comment by sbenthall** [comment]
CSV dump available temporarily here:

http://ischool.berkeley.edu/~sb/icann.tar.gz

To make one yourself, from your /bigbang directory, use the following commands:

```
find ./archives -name '*.csv' -exec tar -rvf icann.tar {} \;
gzip icann.tar
```

Should create a file icann.tar.gz ready for export. For me this file is 133 MB when compressed. More like
