### ISSUE TITLE
beautifulsoup4 not installed with conda install instructions

### ISSUE THREAD

**Issue by sbenthall** [nllz/bigbang#11]
This is in the pip requirements but apparently not in the conda installation requirements yet.

Quick solution: add the dependency to conda-setup.sh

But also, see this ticket about switching to configuration.yml for the conda environment setup.

https://github.com/sbenthall/bigbang/issues/248

**Comment by nllz** [comment]
Shall I add beautifulsoup4 to https://github.com/nllz/bigbang/blob/master/conda-requirements.txt ?

**Comment by sbenthall** [comment]
sure :)

**Comment by nllz** [comment]
https://anaconda.org/anaconda/beautiful-soup is already in there, should I exchange or add https://anaconda.org/anaconda/beautifulsoup4 ?

**Comment by sbenthall** [comment]
yes. i don't recall why there was a different (older?) beautiful-soup dependency

**Comment by nllz** [comment]
exchanged https://github.com/nllz/bigbang/blob/master/conda-requirements.txt
