### ISSUE TITLE
archive paths using URL paths

### ISSUE THREAD

**Issue by sbenthall** [nllz/bigbang#14]
When downloading archives, BigBang is using the full URL (e.g. http://mm.icann.org/pipermail/zfa-cost ) as a file system path.

This makes it confusing to find the .csv files for each list.

**Comment by sbenthall** [comment]
I'm not sure this is a bug, actually. Maybe it's a feature.

Do you have an opinion?

**Comment by nllz** [comment]
Let me understand the usecase clearly: One can import the whole CSV into a notebook, but one would still need to enter the whole URL to analyse the specific mailinglist, right? 

In that case using the full URL is probably a feature, else we might get collisions with bigger data sets.

Adding all the single URLs might be painful, but I think that's what it is, right?
