### ISSUE TITLE
Update install wiki with download and unzip csv + install nits

### ISSUE THREAD

**Issue by nllz** [nllz/bigbang#16]

**Comment by davidberra** [comment]
@sbenthall  I tried to install everything on a windows machine here. followed Niels' intructions, everything seems to be fine (except for Levehnstein module that requires C++ compiler v9, indeed I downloaded it)

but i get 'Error no module named...' on bigbang owns' libraries when importing them from notebooks


do you have any idea what may I be missing out? (I already successfully installed everything on my windows machine)

**Comment by nllz** [comment]
This is something for all of us to review at 17:30 today and possibly earlier @sbenthall @davidberra
