### ISSUE TITLE
Unicode issue with mass import mailinglists

### ISSUE THREAD

**Issue by nllz** [nllz/bigbang#3]
Specifically while importing:

https://github.com/nllz/bigbang/blob/master/examples/mm.icann.org.txt

and

https://github.com/nllz/bigbang/blob/master/examples/mm.ietf.org.txt

**Comment by sbenthall** [comment]
It looks like some of the text is in Korean.

[2006-07.mail.txt](https://github.com/nllz/bigbang/files/326667/2006-07.mail.txt)

**Comment by sbenthall** [comment]
Interesting. Googling for the error, it looks like it may be unique to mailman and email in particular

`LookupError: unknown encoding: x-unknown`

http://grokbase.com/t/python/mailman-developers/044twtyy43/mails-shunt-lookuperror-unknown-encoding-x-unknown

https://mail.python.org/pipermail/mailman-coders/2004-April/001054.html

https://github.com/snyderp/pygmail/issues/1

**Comment by nllz** [comment]
Am not sure if all errors I get when I do $python bin/collect_mail.py -f examples/mm.icann.org.txt can be attributed to Korean (especially since if I then remove a problematic mailinglist from the file, I'll run in to problems with another list, same with the IETF lists (example/mm.ietf.org.txt) for that matter.

**Comment by sbenthall** [comment]
Good call.

Trying to isolate examples of the problem. One is the email with ID 

`<Pine.GSO.4.64.0906040915000.16060@tin>`

in the attached file.
[2009-06.mail.txt](https://github.com/nllz/bigbang/files/328314/2009-06.mail.txt)

I've copied it into this gist out of Emacs

https://gist.github.com/sbenthall/97c6e2c82896679c2cbf8ec52fc2a5d3

You can see where Emacs did what it could to decode the original file. Looks like maybe some of the problematic characters are in somebody's signature?

**Comment by sbenthall** [comment]
Oh, I see now.

Look at this line:

https://gist.github.com/sbenthall/97c6e2c82896679c2cbf8ec52fc2a5d3#file-gistfile1-txt-L47

There is an encoding specified, "x-unknown", which is...unknown. That seems to be causing the error.

**Comment by sbenthall** [comment]
There appears to be only one email in the 16ng corpus with this problem.

**Comment by sbenthall** [comment]
Maybe it's also in `<Pine.GSO.4.64.0906101255320.9230@tin>`

**Comment by sbenthall** [comment]
Commit fixes the 16ng problems here:

https://github.com/nllz/bigbang/commit/81e3816432ac2c566feb6c20da173fb0682d0e64

**Comment by nllz** [comment]
It seems that you're focusing now on example/mm.ietf.org.txt, but https://github.com/nllz/bigbang/blob/master/examples/mm.icann.org.txt has priority because we'll primarily be researching ICANN. IETF lists is a nice to have, ICANN lists is a must have.

**Comment by nllz** [comment]
Does https://github.com/nllz/bigbang/commit/81e3816432ac2c566feb6c20da173fb0682d0e64 fix problems for both?

**Comment by sbenthall** [comment]
Not sure. Thanks for reminding me that ICANN is the priority. I'll shift over to that.

I think I started working on IETF because when I run the collection script for ICANN, I get an error that is not a unicode error. I'll make a separate ticket for that.

**Comment by nllz** [comment]
Yeah, I am getting:

$ source ~/Data/Anaconda2/bin/activate bigbang
$ python bin/collect_mail.py -f examples/
$ python bin/collect_mail.py -f examples/mm.icann.org.txt
/home/gogol/Data/bigbang/bigbang/mailman.py:105: UserWarning: No mailing list name found at http://mm.icann.org/pipermail/absdt
  warnings.warn("No mailing list name found at %s" % url)
'Getting archive page for http://mm.icann.org/pipermail/absdt'
['2011-January.txt.gz',
 '2010-December.txt.gz',
 '2010-November.txt.gz',
 '2010-October.txt.gz',
 '2010-September.txt.gz',
 '2010-July.txt.gz',
 '2010-June.txt.gz',
 '2010-May.txt.gz',
 '2010-April.txt.gz',
 '2010-March.txt.gz',
 '2010-February.txt.gz']
'retrieving http://mm.icann.org/pipermail/absdt2011-January.txt.gz'
Traceback (most recent call last):
  File "bin/collect_mail.py", line 41, in <module>
    main(sys.argv[1:])
  File "bin/collect_mail.py", line 38, in main
    mailman.collect_from_file(arg)
  File "/home/gogol/Data/bigbang/bigbang/mailman.py", line 94, in collect_from_file
    collect_from_url(url)
  File "/home/gogol/Data/bigbang/bigbang/mailman.py", line 80, in collect_from_url
    collect_archive_from_url(url)
  File "/home/gogol/Data/bigbang/bigbang/mailman.py", line 142, in collect_archive_from_url
    resp = urllib2.urlopen(gz_url)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/gogol/Data/Anaconda2/envs/bigbang/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

**Comment by sbenthall** [comment]
@nllz  Have you seen any unicode errors besides the one fixed by this ticket?
If not I can close this.

**Comment by nllz** [comment]
importing now - feeling the power :)

**Comment by sbenthall** [comment]
assuming the unicode error is fixed for now.

if you see any other issues, please open a separate ticket for them.
