### ISSUE TITLE
Create Notebook(s) for Summerschool

### ISSUE THREAD

**Issue by nllz** [nllz/bigbang#4]
Create one to three notebooks that are easy to use with imported dataset (ICANN relevant).

These will be ipnyb notebooks that students can download and run with the csv data set that will be prepared for them. This way everyone can use their own laptop

**Comment by jwyg** [comment]
Three notebooks:

  * Words + special words
  * Community
  * Intercommunity

**Comment by nllz** [comment]
1. Single words https://github.com/nllz/bigbang/blob/master/examples/SummerSchoolMultipleWordAnalysis.ipynb

2. Senders replyers
https://github.com/nllz/bigbang/blob/master/examples/SummerSchoolSendersRepliersAnalysis.ipynb
