### ISSUE TITLE
Create how-to (preferably on a website with the data)

### ISSUE THREAD

**Issue by nllz** [nllz/bigbang#5]
This will be a step by step how-to so that students can download and run the notebook with the csv data set that will be prepared for them. This way everyone can use their own laptop for the research.

**Comment by jwyg** [comment]
Installing Jupyter: https://jupyter.readthedocs.io/en/latest/install.html

**Comment by davidberra** [comment]
apparently, the easiest way to have Jupyter on Windows is...to install Anaconda. Went smooth to me but dependencies issues may rise on others laptops...

**Comment by nllz** [comment]
I think it's done: https://github.com/nllz/bigbang/wiki

**Comment by nllz** [comment]
We only need the download links to the csv from @sbenthall and the notebooks from @davidberra and then some testing from @jwyg ¯\_(ツ)_/¯

**Comment by nllz** [comment]
CSV dump available temporarily here:

http://ischool.berkeley.edu/~sb/icann.tar.gz

To make one yourself, from your /bigbang directory, use the following commands:

find ./archives -name '*.csv' -exec tar -rvf icann.tar {} \;
gzip icann.tar
Should create a file icann.tar.gz ready for export. For me this file is 133 MB when compressed. More like
